centrifuge/src/main/java/io/github/centrifugal/centrifuge/Subscription.java
example/src/main/java/io/github/centrifugal/centrifuge/example/Main.java

Fixes #9 
The reason was that Subscription method futures have never been executed in case of Subscription in Subscribed state.

Fix not executing Subscription methods in subscribed state

---

README.md
centrifuge/build.gradle
gradle/wrapper/gradle-wrapper.properties

Some tweaks to work with Gradle 7. We are using `maven-publish` plugin instead of `maven` now.

Migrate to Gradle 7

---

centrifuge/src/main/java/io/github/centrifugal/centrifuge/Client.java

This will allow omit `?format=protobuf` when working with Centrifugo v3 and Centrifuge >= v0.18.0

Subprotocol to avoid URL param

---

centrifuge/src/main/java/io/github/centrifugal/centrifuge/Client.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/ClientInfo.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/PublishEvent.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/ServerPublishEvent.java

In `centrifuge-go` a publish event (Publication struct) has 3 values - `Offset`, `Data` and `Info` ([view implementation](https://github.com/centrifugal/centrifuge-go/blob/595eded263578dd44cb6f2b6a8d3a08ac34b8f4a/protocol.go#L18)). But the java client only has 2 - offset and data.
This commit adds `info` to the `PublishEvent` class and sets it in the Client class.

fix PublishEvent: Add ClientInfo

---

centrifuge/src/main/java/io/github/centrifugal/centrifuge/Client.java
example/src/main/java/io/github/centrifugal/centrifuge/example/Main.java

In some scenarios onFailure can be called while connection is in CONNECTED state. For example, by setting reliability to 0% in Charles Proxy during live connection I was able to get EOF exception in onFailure, and `onClosed` callback never called in this case. According to okhttp docs for https://square.github.io/okhttp/4.x/okhttp/okhttp3/-web-socket-listener/on-failure/
> Invoked when a web socket has been closed due to an error reading from or writing to the network. Both outgoing and incoming messages may have been lost. No further calls to this listener will be made.
So we need to schedule reconnect in any case from the onFailure handler.
This can fix broken reconnect in some cases where internet connection was missing for some time.

Fix reconnect after onFailure

---

centrifuge/src/main/java/io/github/centrifugal/centrifuge/Client.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/Dns.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/Options.java

We need to connect to centrifuge server using custom DNS. Currently have to use custom build of this library to achieve this.
This PR adds ability to pass custom DNS client through `Options`.

Custom DNS client for connecting to centrifuge server

---

.github/workflows/ci.yml
.github/workflows/release.yml
README.md

Inspired by centrifuge-js, this PR adds 2 GitHub workflows.
1. `ci.yml` checks compilation of the library and samples, and runs unit tests
2. `release.yml` builds and publishes the library by tag to Maven Central
It basically resolves both #11 and #42 issues.
Will not be able to test release workflow. But Test workflow works:

Basic GitHub Actions for CI/CD

---

README.md
centrifuge/src/main/resources/META-INF/proguard/centrifuge-java.pro

Android consumers don't need to add ProGuard rules manually. The library will supply the rules in jar file. This is a standard mechanism of ProGuard for library developers.
Tested this with Android app.

Include consumer proguard rules

---

.github/workflows/ci.yml
README.md
build.gradle
centrifuge/api.txt
centrifuge/build.gradle

One of the things we could find helpful in library development is compatibility checks.
Sometimes, it is unclear if we did any breaking change. Which version should we increment, minor or major?
There is a plugin for Gradle that allows to capture the state of the API and verify change for compatibility against that state. The plugin is [metalava-gradle](https://github.com/tylerbwong/metalava-gradle).
To generate API fixtures use the following command:
```shell
./gradlew :centrifuge:metalavaGenerateSignature
```
To verify API compatibility, run the following command:
```shell
./gradlew :centrifuge:metalavaCheckCompatibility
```

API compatibility check on CI

---

centrifuge/src/main/java/io/github/centrifugal/centrifuge/Client.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/ConfigurationError.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/UnclassifiedError.java

Relates #49 
This pr:
1. Puts the source of bad protocol disconnect to reason to differentiate upon happening without finding a printed stacktrace. Also send the exception to `onError` listener.
2. Replace DISCONNECTED_BAD_PROTOCOL with DISCONNECTED_UNAUTHORIZED for the configuration error when TokenGetter not set. Also, send ConfigurationError to Error listener in this case.
3. Fix unsubscribe request which used legacy command.

Fix unsubscribe request, bad protocol diffirentiation

---

centrifuge/src/main/java/io/github/centrifugal/centrifuge/Client.java
demo/src/main/java/io/github/centrifugal/centrifuge/demo/MainActivity.java
example/src/main/java/io/github/centrifugal/centrifuge/example/Main.java

Allows authenticating for private channels. Fixes #52

add SubscriptionOptions parameter to newSubscription

---

centrifuge/src/main/java/io/github/centrifugal/centrifuge/Client.java

Right now when I call `disconnect`, `EventListener.onError` is getting called with the following exception stacktrace:
```
java.net.SocketException: Socket closed
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
at java.net.SocketInputStream.read(SocketInputStream.java:173)
at java.net.SocketInputStream.read(SocketInputStream.java:143)
at okio.InputStreamSource.read(JvmOkio.kt:94)
at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:128)
at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
at okio.RealBufferedSource.readByte(RealBufferedSource.kt:209)
at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
at …
```

Disconnect gracefully

---

centrifuge/build.gradle
centrifuge/src/main/java/io/github/centrifugal/centrifuge/Client.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/CompletionCallback.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/Dns.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/RefreshError.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/ResultCallback.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/ServerSubscribedEvent.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/SubscribedEvent.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/Subscription.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/TokenCallback.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/package-info.java

Right now, when used from Kotlin, library generates a lot of optional parameters - that's default behaviour for Java interop, as there's no build-in nullability checks.
```
object : SubscriptionEventListener() {
override fun onSubscribed(sub: Subscription?, event: SubscribedEvent?) {
}
```
With this PR I've added `ParametersAreNonnullByDefault` annotation to the lib package - this makes all arguments non nullable by default for IDEA linter and for Kotlin interop.
Also I've added a couple `Nullable` annotation for parameters that actually can be null - after adding `@ParametersAreNonnullByDefault`, IDEA showed me such places with warnings.
Also fixed a couple of warned placed

And nullable/nonnullable annotation to improve Kotlin API

---

centrifuge/src/main/java/io/github/centrifugal/centrifuge/ConfigurationError.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/Options.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/PresenceResult.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/RefreshError.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/ResultCallback.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/SubscriptionErrorEvent.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/SubscriptionRefreshError.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/SubscriptionSubscribeError.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/SubscriptionTokenError.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/SubscriptionTokenEvent.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/TokenError.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/UnclassifiedError.java

Use super for errors to propagate cause

---

centrifuge/src/main/java/io/github/centrifugal/centrifuge/Client.java

Handle closed executor in ws callbacks

---

README.md
centrifuge/build.gradle

`cfuture` is relatively small (66KB), but it depends on `streamsupport`, which is 958KB.
On the other hand `minifuture` is only 104KB and has no dependencies.
- Replace `cfuture` with `minifuture`
- Add workaround to Readme to mitigate class conflicts with streamsupport libs.

Replace cfuture with minifuture

---

centrifuge/src/main/java/io/github/centrifugal/centrifuge/Client.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/ErrorEvent.java

Add HTTP response code to ErrorEvent.
There is an alternative approach to [this PR](https://github.com/centrifugal/centrifuge-java/pull/68).
In my opinion it would be better to pass whole response to ErrorEvent, but it will expose okhttp in centrifuge API.
Our project needs an ability to change an endpoint in case of specific errors:
- UnknownHostException, SocketTimeoutException
- Some subset of HTTP response codes. For example 410
HTTP status codes currently does not exposed by centrifuge SDK, so we do not know when we need to change endpoint.

Add HTTP response code to ErrorEvent

---

centrifuge/src/main/java/io/github/centrifugal/centrifuge/Client.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/Subscription.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/SubscriptionOptions.java
example/src/main/java/io/github/centrifugal/centrifuge/example/Main.java

This PR:
* adds delta support in recovered publications in addition to new publications added in #74 
* makes getPrevData/setPrevData private as should not be used from the outside
* adds `since` option for Subscription to provide starting `StreamPosition` for the Subscription.

Delta improvements, introducing since option

---

centrifuge/build.gradle
publish-setup.gradle

This helps to avoid [CVE-2024-7254](https://ossindex.sonatype.org/vulnerability/CVE-2024-7254) in Protobuf library.

Bump protobuf-javalite version

---

centrifuge/src/main/java/io/github/centrifugal/centrifuge/Client.java
centrifuge/src/main/java/io/github/centrifugal/centrifuge/Options.java

This PR adds the ability to set a custom `SSLSocketFactory` for the `OkHttpClient`
This is particularly useful for adding new CA certificates, or using self-signed certificates for debugging purposes

Custom SSLSocketFactory
